### ISSUE TITLE
push docker/binfmt to dockerhub?

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/binfmt#15]
@StefanScherer @tonistiigi

**Comment by StefanScherer** [comment]
It‘s pushed to https://hub.docker.com/r/docker/binfmt/tags

Tag 820fdd95a9972a5308930a2bdfb8573dd4447ad3 is the newest with QEMU 4.0.0.

**Comment by AkihiroSuda** [comment]
Oh, I didn't notice because it doesn't have `latest` tag :sweat_smile:
