### ISSUE TITLE
Push tags to dockerhub

### ISSUE THREAD

**Issue by umarcor** [docker/binfmt#16]
As commented in #15, images are pushed to dockerhub (hub.docker.com/r/docker/binfmt/tags), but there are digests only, no tags. It'd be useful to have `docker/binfmt:latest` and `docker/binfmt:4.0.0` available.

**Comment by StefanScherer** [comment]
I understand that this would be useful. In our build pipeline we directly use the digest.

**Comment by justincormack** [comment]
This repo is deprecated in favour of https://github.com/linuxkit/linuxkit/tree/master/pkg/binfmt
