### ISSUE TITLE
Information on the installation process

### ISSUE THREAD

**Issue by fgervais** [docker/binfmt#20]
This kind of installation through docker is pretty novel to me.

Could somebody provide some information on how this works?

I normally use my distribution's provided packages to setup binfmt. However, in this case I feel like I'll have a better chance of having buildx running if I use this image since it provides a version of qemu specifically patched for that purpose. Will the installation through this image interfere with the linux distribution packages in some way?

One last thing, once I run this image, where do the qemu-* binaries resides?

**Comment by justincormack** [comment]
In general your distro's packages should work fine, at least if it is a recent Qemu. We are upstreaming our changes as much as we can. The main purpose originally was for Docker Desktop and other places where packages are not easily available.

The binaries remain inside the container, the kernel keeps a file handle open to them.

**Comment by fgervais** [comment]
Thank you @justincormack
