### ISSUE TITLE
"bad record MAC" for linux/s390x

### ISSUE THREAD

**Issue by dims** [docker/binfmt#23]
I am running into the following error:
```
#11 [builder 5/8] RUN go mod download
#11 0.445 go: github.com/pkg/errors@v0.9.1: Get https://proxy.golang.org/github.com/pkg/errors/@v/v0.9.1.mod: local error: tls: bad record MAC
#11 ERROR: executor failed running [/bin/sh -c go mod download]: buildkit-runc did not terminate successfully
```

I am using buildx under GCB - https://github.com/dims/go-runner.Looks like the same problem was spotted in another arch as well https://github.com/moby/moby/issues/40240

Per https://bugs.launchpad.net/qemu/+bug/1847232, the problem has been fixed in QEMU 4.2

**Comment by justincormack** [comment]
Please use LinuxKit instead https://github.com/linuxkit/linuxkit/pull/3515
